title: Josh's blog
author: Urtica-dioica
email: info@mcdonalds.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Learn about coding and all the cool projects that I've built

# social links
twitter_username: josh_does_code # DO NOT include the @ character, or else the build will fail!
github_username:  Urtica-dioica # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
